work_dir: ./work_dir/ntu/xview/aagcn_joint
model_saved_name: ./runs/ntu_cv_aagcn_joint
# feeder
feeder: feeders.feeder_rgn.Feeder
test_feeder_args:
  joint_data_path: ./data/nturgbd_raw/ntu/xview/val_data_joint.npy
  bone_data_path: ./data/nturgbd_raw/ntu/xview/val_data_bone.npy
  label_path: ./data/nturgbd_raw/ntu/xview/val_label.pkl
  debug: False

# model
model: model.dgnn_base.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.directed_ntu_rgb_d.Graph

# test
phase: test
device: [0]
test_batch_size: 64
weights: runs/ntu_cv_aagcn_joint-41-8379.pt
save_score: True
