work_dir: ./work_dir/ntu/xview/dgnn_spatial
model_saved_name: ./runs/ntu_cs_dgnn_spatial
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  joint_data_path: ./data/nturgbd_raw/ntu/xview/train_data_joint.npy
  bone_data_path: ./data/nturgbd_raw/ntu/xview/train_data_bone.npy
  label_path: ./data/nturgbd_raw/ntu/xview/train_label.pkl

  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  joint_data_path: ./data/nturgbd_raw/ntu/xview/val_data_joint.npy
  bone_data_path: ./data/nturgbd_raw/ntu/xview/val_data_bone.npy
  label_path: ./data/nturgbd_raw/ntu/xview/val_label.pkl

# model
model: model.dgnn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.directed_ntu_rgb_d.Graph

# optim
weight_decay: 0.0005
base_lr: 0.1
step: [15,25,40]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 50
nesterov: True
freeze_graph_until: 5  # Number of epochs until graphs can be updated

only_train_part: True
only_train_epoch: 5

