work_dir: ./work_dir/ntu/xsub/aagcn_joint
model_saved_name: ./runs/ntu_cs_aagcn_joint
# feeder
feeder: feeders.feeder_rgn.Feeder
train_feeder_args:
  joint_data_path: ./data/nturgbd_raw/ntu/xsub/train_data_joint.npy
  bone_data_path: ./data/nturgbd_raw/ntu/xsub/train_data_bone.npy
  label_path: ./data/nturgbd_raw/ntu/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  joint_data_path: ./data/nturgbd_raw/ntu/xsub/val_data_joint.npy
  bone_data_path: ./data/nturgbd_raw/ntu/xsub/val_data_bone.npy
  label_path: ./data/nturgbd_raw/ntu/xsub/val_label.pkl

# model
model: model.dgnn_base.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.directed_ntu_rgb_d.Graph

#optim
weight_decay: 0.0005
base_lr: 0.1
step: [40, 80]
warm_up_epoch: 1

# training
device: [0, 1, 2, 3]
batch_size: 128
test_batch_size: 128
num_epoch: 120
nesterov: True

only_train_part: False
only_train_epoch: 5
# weights: runs/ntu_cs_aagcn_joint-51-4164.pt

